.PHONY: clean All

All:
	@echo "----------Building project:[ meteor2 - Debug ]----------"
	@cd "meteor2" && "$(MAKE)" -f  "meteor2.mk"
clean:
	@echo "----------Cleaning project:[ meteor2 - Debug ]----------"
	@cd "meteor2" && "$(MAKE)" -f  "meteor2.mk" clean
