.PHONY: clean All

All:
	@echo "----------Building project:[ climb - Debug ]----------"
	@cd "climb" && "$(MAKE)" -f  "climb.mk"
clean:
	@echo "----------Cleaning project:[ climb - Debug ]----------"
	@cd "climb" && "$(MAKE)" -f  "climb.mk" clean
