.PHONY: clean All

All:
	@echo "----------Building project:[ shuffle - Debug ]----------"
	@cd "shuffle" && "$(MAKE)" -f  "shuffle.mk"
clean:
	@echo "----------Cleaning project:[ shuffle - Debug ]----------"
	@cd "shuffle" && "$(MAKE)" -f  "shuffle.mk" clean
