.PHONY: clean All

All:
	@echo "----------Building project:[ stuck2 - Debug ]----------"
	@cd "stuck2" && "$(MAKE)" -f  "stuck2.mk"
clean:
	@echo "----------Cleaning project:[ stuck2 - Debug ]----------"
	@cd "stuck2" && "$(MAKE)" -f  "stuck2.mk" clean
