.PHONY: clean All

All:
	@echo "----------Building project:[ stalls2 - Debug ]----------"
	@cd "stalls2" && "$(MAKE)" -f  "stalls2.mk"
clean:
	@echo "----------Cleaning project:[ stalls2 - Debug ]----------"
	@cd "stalls2" && "$(MAKE)" -f  "stalls2.mk" clean
