.PHONY: clean All

All:
	@echo "----------Building project:[ homework - Debug ]----------"
	@cd "homework" && "$(MAKE)" -f  "homework.mk"
clean:
	@echo "----------Cleaning project:[ homework - Debug ]----------"
	@cd "homework" && "$(MAKE)" -f  "homework.mk" clean
